server:
  port: 8091
spring:
  application:
    name: Spring Boot Data JPA Using MOngoDB
      data:    mongodb:      host: localhost      port: 27017
      database: student
      
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging:  level:    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-index.html
  api-docs:
    enabled: true
    path: /swagger-index.doc
    
